TicketsDemo/Models/CreateTicketModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TicketsDemo.Models
{
    public class CreateTicketModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ReservationId { get; set; }
    }
}

TicketsDemo/Models/IndexPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class IndexPageViewModel
    {
        public DateTime ScheduleStart { get; set; }
        public DateTime ScheduleEnd { get; set; }
        public List<Run> Runs { get; set; }
        public Dictionary<int,Train> Trains { get; set; }
    }
}

TicketsDemo/Models/ReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class ReservationViewModel
    {
        public DateTime Date { get; set; }
        public Train Train { get; set; }
        public Reservation Reservation { get; set; }
        public PlaceInRun PlaceInRun { get; set; }
        public List<PriceComponent> PriceComponents { get; set; }
    }
}

TicketsDemo/Models/RunViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class RunViewModel
    {
        public Train Train { get; set; }

        public DateTime RunDate { get; set; }

        public Dictionary<int, Carriage> Carriages { get; set; }

        public Dictionary<int, List<PlaceInRun>> PlacesByCarriage { get; set; }

        public List<int> ReservedPlaces { get; set; }
    }
}

TicketsDemo/Models/TicketViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class TicketViewModel
    {
        public Ticket Ticket { get; set; }

        public Train Train { get; set; }

        public DateTime Date { get; set; }

        public int PlaceNumber { get; set; }
    }
}

TicketsDemo/Models/TrainDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class TrainDetailsViewModel
    {
        public DateTime ScheduleStart { get; set; }
        public DateTime ScheduleEnd { get; set; }
        public Train Train { get; set; }
        public List<Run> Runs { get; set; }
        public List<DateTime> AvailableDates { get; set; }
    }
}

TicketsDemo/Controllers/RunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketsDemo.Data.Repositories;
using TicketsDemo.Domain.Interfaces;
using TicketsDemo.Models;

namespace TicketsDemo.Controllers
{
    public class RunController : Controller
    {
        private ITicketRepository _tickRepo;
        private IRunRepository _runRepo;
        private IReservationRepository _reservationRepo;
        private IReservationService _resServ;
        private ITicketService _tickServ;
        private IPriceCalculationStrategy _priceCalc;
        private ITrainRepository _trainRepo;

        public RunController(ITicketRepository tick, IRunRepository run, 
            IReservationService resServ,
            ITicketService tickServ,
            IPriceCalculationStrategy priceCalcStrategy,
            IReservationRepository reservationRepo,
            ITrainRepository trainRepo) {
            _tickRepo = tick;
            _runRepo = run;
            _resServ = resServ;
            _tickServ = tickServ;
            _priceCalc = priceCalcStrategy;
            _reservationRepo = reservationRepo;
            _trainRepo = trainRepo;
        }

        public ActionResult Index(int id) {
            var run = _runRepo.GetRunDetails(id);
            var train = _trainRepo.GetTrainDetails(run.TrainId);
            var model = new RunViewModel() {
                RunDate = run.Date,
                Carriages = train.Carriages.ToDictionary(x => x.Number),
                PlacesByCarriage = run.Places.GroupBy(x => x.CarriageNumber).ToDictionary(x => x.Key, x => x.ToList()),
                ReservedPlaces = run.Places.Where(p => _resServ.PlaceIsOccupied(p)).Select(p => p.Id).ToList(),
                Train = train,
            };

            return View(model);
        }

        public ActionResult ReservePlace(int placeId) {
            var place = _runRepo.GetPlaceInRun(placeId);

            var reservation = _resServ.Reserve(place);

            var model = new ReservationViewModel()
            {
                Reservation = reservation,
                PlaceInRun = place,
                PriceComponents = _priceCalc.CalculatePrice(place),
                Date = place.Run.Date,
                Train = _trainRepo.GetTrainDetails(place.Run.TrainId),
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateTicket(CreateTicketModel model)
        {
            var tick = _tickServ.CreateTicket(model.ReservationId,model.FirstName,model.LastName);
            return RedirectToAction("Ticket", new { id = tick.Id });
        }

        public ActionResult Ticket(int id)
        {
            var ticket = _tickRepo.Get(id);
            var reservation = _reservationRepo.Get(ticket.Id);
            var placeInRun = _runRepo.GetPlaceInRun(reservation.PlaceInRunId);

            var ticketWM = new TicketViewModel();
            ticketWM.Ticket = ticket;
            ticketWM.PlaceNumber = placeInRun.Number;
            ticketWM.Date = placeInRun.Run.Date;
            ticketWM.Train = _trainRepo.GetTrainDetails(placeInRun.Run.TrainId);

            return View(ticketWM);
        }

    }
}

TicketsDemo/Controllers/ScheduleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TicketsDemo.Data.Repositories;
using TicketsDemo.Domain.Interfaces;
using TicketsDemo.Models;

namespace TicketsDemo.Controllers
{
    public class ScheduleController : Controller
    {
        private ISchedule _schedule;
        private ITrainRepository _trainRepo;
        private IRunRepository _runRepo;

        public ScheduleController(ISchedule schedule, ITrainRepository trainRepo, IRunRepository runRepo) {
            _schedule = schedule;
            _trainRepo = trainRepo;
            _runRepo = runRepo;
        }

        public ActionResult Index()
        {
            var startDate = DateTime.Now;
            var endDate = startDate.AddMonths(1);
            var model = new IndexPageViewModel()
            {
                ScheduleStart = startDate,
                ScheduleEnd = endDate,
                Runs = _runRepo.GetRuns(startDate, endDate),
                Trains = _trainRepo.GetAllTrains().ToDictionary(x => x.Id)
            };

            return View(model);
        }

        public ActionResult Train(int id) {
            var startDate = DateTime.Now;
            var endDate = startDate.AddMonths(1);
            var model = new TrainDetailsViewModel()
            {
                ScheduleStart = startDate,
                ScheduleEnd = endDate,
                Runs = _runRepo.GetRuns(startDate, endDate,id),
                Train = _trainRepo.GetTrainDetails(id),
                AvailableDates = _schedule.GetAvailableDatesForNewRun(id,startDate,endDate)
            };
            
            return View(model);      
        }
        
        public ActionResult CreateRun(int trainId, DateTime date) {
            _schedule.CreateRun(trainId, date);
            return RedirectToAction("Train", new { id = trainId });
        }

        public ActionResult DeleteRun(int id)
        {
            _schedule.DeleteRun(id);
            return RedirectToAction("Train", new { id = id });
        }
    }
}

TicketsDemo/Views/Run/Index.cshtml
@model TicketsDemo.Models.RunViewModel

@{
    ViewBag.Title = "Run details";
}

<h2>Train @Model.Train.Number (@Model.Train.StartLocation - @Model.Train.EndLocation)</h2>
<h4>Run starts at @Model.RunDate.ToShortDateString()</h4>

<h2>Available Places</h2>

@foreach (var carriageNumber in Model.PlacesByCarriage.Keys)
{
    var placesInCarriage = Model.PlacesByCarriage[carriageNumber];
    <div> 
        <h4> Carriage @carriageNumber, @Model.Carriages[carriageNumber].Type</h4>
        @foreach (var place in placesInCarriage)
        {
            if (Model.ReservedPlaces.Contains(place.Id))
            {
                @place.Number;
            }
            else
            {
            <a href="@Url.Action("ReservePlace", new { placeId = place.Id })">@place.Number</a>
            }
        }
    </div>
}

TicketsDemo/Views/Run/ReservePlace.cshtml
@model TicketsDemo.Models.ReservationViewModel

@{
    ViewBag.Title = "Run details";
}

<h2>Train @Model.Train.Number (@Model.Train.StartLocation - @Model.Train.EndLocation)</h2>
<h4>Run starts at @Model.Date.ToShortDateString()</h4>

<h2>the place @Model.PlaceInRun.Number in carriage @Model.PlaceInRun.CarriageNumber is reserved for you for</h2>

<h4>Price:</h4>

@foreach (var pc in Model.PriceComponents) { 
    <span>@pc.Name:@pc.Value$</span><br />
}

@using (Html.BeginForm("CreateTicket","Run"))
{ 
    <input type="hidden" value="@Model.Reservation.Id" name="ReservationId" id="ReserevationId"/>
    <table>
        <tr>
            <td>First Name</td>
            <td><input type="text" name="FirstName" id="FirstName" /></td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td><input type="text" name="LastName" id="LastName" /></td>
        </tr>
    </table>
    <input type="submit" value="submit"/>
}

<!--public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ReservationId { get; set; }-->

TicketsDemo/Views/Run/ticket.cshtml
@model TicketsDemo.Models.TicketViewModel

@{
    ViewBag.Title = "Ticket details";
}

<h2>Train @Model.Train.Number (@Model.Train.StartLocation - @Model.Train.EndLocation)</h2>
<h4>Run starts at @Model.Date.ToShortDateString()</h4>

<h2>ticket is for place @Model.PlaceNumber</h2>

<h4>Price:</h4>
@foreach (var pc in Model.Ticket.PriceComponents) { 
    <span>@pc.Name:@pc.Value$</span><br />
}

<!--public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ReservationId { get; set; }-->

TicketsDemo/Views/Schedule/Index.cshtml
@model TicketsDemo.Models.IndexPageViewModel

@{
    ViewBag.Title = "Index";
}

    <h2>Recommended paths</h2>
@foreach (var train in Model.Trains) { 
    <a href="@Url.Action("Train",new {id = train.Value.Id})">@train.Value.Number (@train.Value.StartLocation - @train.Value.EndLocation)</a><br />
}

<h2>Train runs schedule between @Model.ScheduleStart.ToShortDateString() and @Model.ScheduleEnd.ToShortDateString()</h2>

@foreach (var run in Model.Runs.OrderBy(m => m.Date)) { 
    <a href="@Url.Action("Index","Run",new {id = run.Id})">@run.Date.ToShortDateString(),train:@Model.Trains[run.TrainId].Number</a> <br />
}

TicketsDemo/Views/Schedule/Train.cshtml
@model TicketsDemo.Models.TrainDetailsViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Train @Model.Train.Number (@Model.Train.StartLocation - @Model.Train.EndLocation)</h2>
@foreach (var carriage in Model.Train.Carriages) { 
   <h4>@carriage.Type.ToString()</h4>
    foreach (var place in carriage.Places) { 
        @place.Number<text>,</text>
    }
}

<h2>Schedule between the @Model.ScheduleStart.ToShortDateString() and @Model.ScheduleEnd.ToShortDateString()</h2>

@foreach (var run in Model.Runs.OrderBy(m => m.Date)) { 
    <a href="@Url.Action("Index","Run",new {id = run.Id})">@run.Date.ToShortDateString(),train:@Model.Train.Number</a> <br />
}

<h2>Create new Run</h2>
@foreach (var date in Model.AvailableDates) { 
    <a href="@Url.Action("CreateRun",new {trainId = Model.Train.Id,date=date})">at @date.ToShortDateString()</a> <br />
}